name: Generate new release for plugin

on:
  pull_request:
    types: [ closed ]
    branches: [ main ]

env:
  PLUGIN_NAME: integration-rede-for-woocommerce
  DIR_NAME: woo-rede
  PHP_VERSION: "7.4"
  DEPLOY_TAG: "3.7.3"

jobs:
  release-build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ env.PHP_VERSION }}
        coverage: none

    # Plugin check
    - name: Install PHP_CodeSniffer and WordPress Standards
      run: |
        composer global require "squizlabs/php_codesniffer=*"
        composer global require "wp-coding-standards/wpcs"
        ~/.composer/vendor/bin/phpcs --config-set installed_paths ~/.composer/vendor/wp-coding-standards/wpcs
        ~/.composer/vendor/bin/phpcs -i

    - name: Run PHPCS with custom ruleset
      run: |
        export PATH="$HOME/.composer/vendor/bin:$PATH"
        phpcs --warning-severity=0

    - name: Run composer install
      uses: php-actions/composer@v6
      with:
        php_version: ${{ env.PHP_VERSION }}
        working_dir: "."
        args: --ignore-platform-reqs
        command: install
        dev: no

    # Add plugin files to a root directory
    - name: Prepare plugin folder
      run: |
        mkdir -p dist
        mkdir -p build/${{ env.PLUGIN_NAME }}
        mv ./Admin ./Includes ./languages ./Public *.php *.txt ./build/${{ env.PLUGIN_NAME }}
        cp -r vendor ./build/${{ env.PLUGIN_NAME }}/vendor
        find ./build -type f -exec chmod 0644 {} +
        find ./build -type d -exec chmod 0755 {} +

    # Compact plugin as .zip
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        path: '.'
        directory: 'build'
        filename: '${{ env.PLUGIN_NAME }}.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'

    - name: Move .zip to custom location
      run: |
        mv ./build/${{ env.PLUGIN_NAME }}.zip ./dist/

    - name: Deploy para WordPress.org
      uses: 10up/action-wordpress-plugin-deploy@stable
      env:
        VERSION: ${{ env.DEPLOY_TAG }}
        SLUG: woo-rede
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        ASSETS_DIR: .wordpress-org
        BUILD_DIR: build/${{ env.PLUGIN_NAME }}

    # Update version tag
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        custom_tag: ${{ env.DEPLOY_TAG }}

    # Generate new release
    - name: Generate new Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "dist/${{ env.PLUGIN_NAME }}.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
        commit: "main"
        draft: true
        tag: ${{ steps.tag_version.outputs.new_tag }}
        name: Release ${{ steps.tag_version.outputs.new_tag }}
